SET SERVEROUTPUT ON;
DECLARE
  TYPE T_ASS_ARRY IS TABLE OF
    EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
    ASS T_ASS_ARRY;
BEGIN
  
  SELECT * INTO ASS(1) FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
  
  DBMS_OUTPUT.PUT_LINE(ASS(1).EMPLOYEE_ID);
END;
