SET SERVEROUTPUT ON;

---1
CREATE OR REPLACE FUNCTION SHOW_EMP_NAME(P_EMP_ID NUMBER) RETURN VARCHAR2
IS
V_EMP_NAME VARCHAR2(100);
BEGIN
  SELECT FIRST_NAME||' '||LAST_NAME
  INTO V_EMP_NAME
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = P_EMP_ID;
  RETURN V_EMP_NAME;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    V_EMP_NAME := 'SUCH NO EMPLOYEE WITH ID: '||P_EMP_ID;
    RETURN V_EMP_NAME;
END;

DECLARE
V_EMP_NAME VARCHAR2(100);
BEGIN
V_EMP_NAME := SHOW_EMP_NAME(&EMP_ID);
DBMS_OUTPUT.PUT_LINE(V_EMP_NAME);
END;


---2
CREATE OR REPLACE FUNCTION SHOW_AVG_SAL(P_DEPT_ID NUMBER) RETURN NUMBER
IS
V_AVG_SAL NUMBER;
BEGIN
  SELECT AVG(SALARY)
  INTO V_AVG_SAL
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = P_DEPT_ID;
  RETURN V_AVG_SAL;
END;

DECLARE
V_AVG_SAL VARCHAR2(100);
V_DEPT_ID NUMBER := &DEPT_ID;
BEGIN
V_AVG_SAL := SHOW_AVG_SAL(V_DEPT_ID);
DBMS_OUTPUT.PUT_LINE('ANERAGE SALARY OF DEPARTMENT ID '||V_DEPT_ID||' IS : '|| V_AVG_SAL);
END;

---3
CREATE OR REPLACE PROCEDURE ADD_DEPT(P_ID NUMBER, P_DEPT_NAME IN OUT VARCHAR2, P_MGR_ID NUMBER, P_LOC_ID NUMBER)
IS
BEGIN
  INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
  VALUES(P_ID,P_DEPT_NAME,P_MGR_ID,P_LOC_ID);
  IF SQL%ROWCOUNT = 1 THEN
   SELECT 'DEPARTMENT ID '||DEPARTMENT_ID||' '||DEPARTMENT_NAME||' '||MANAGER_ID||' '||LOCATION_ID||' IS ADDED' INTO P_DEPT_NAME
   FROM DEPARTMENTS WHERE DEPARTMENT_ID = P_ID;
  END IF;
  
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
   SELECT 'CANT ADD DEPARTMENT ID: '||P_ID||' IT ALREADY EXIST' INTO P_DEPT_NAME
   FROM DUAL;
END;

DECLARE
V_DEPT_NAME VARCHAR2(200) := '&DEPT_NAME';
BEGIN
ADD_DEPT(&ID,V_DEPT_NAME,&MGR_ID,&LOC_ID);
DBMS_OUTPUT.PUT_LINE(V_DEPT_NAME);
END;


--4
CREATE OR REPLACE PROCEDURE COPY_EMP2(P_DEPT_ID IN OUT NUMBER)
IS
CURSOR CUR_S_EMP IS (SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,EMAIL 
                    FROM EMPLOYEES 
                    WHERE DEPARTMENT_ID = P_DEPT_ID);
V_COUNT NUMBER := 0;
BEGIN
  FOR I IN CUR_S_EMP LOOP
    INSERT INTO COPY_EMP(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,EMAIL)
    VALUES(I.EMPLOYEE_ID,I.FIRST_NAME,I.LAST_NAME,I.HIRE_DATE,I.JOB_ID,I.SALARY,I.COMMISSION_PCT,I.MANAGER_ID,I.DEPARTMENT_ID,I.EMAIL);
    V_COUNT := V_COUNT + 1;
  END LOOP;
  P_DEPT_ID:= V_COUNT;
END;
/


SET SERVEROUTPUT ON;
DECLARE
V_DEPT_ID NUMBER := &DEPR_ID;
BEGIN
COPY_EMP2(V_DEPT_ID);
DBMS_OUTPUT.PUT_LINE(V_DEPT_ID||' ROW COPY INTO COPY_EMP TABLE FROM EMPLOYEES WHERE DEPARTMENT ID: '||V_DEPT_ID);
END;


SELECT * FROM COPY_EMP
ROLLBACK;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 40;
