SET SERVEROUTPUT ON
DECLARE
C_PI CONSTANT NUMBER := 3.1416;
V_REDIOUS NUMBER NOT NULL DEFAULT 5;
V_AREA NUMBER;
BEGIN
/*
V_REDIOUS := &A
*/
V_AREA := 2*C_PI*V_REDIOUS*V_REDIOUS;
DBMS_OUTPUT.PUT_LINE('TOTAL AREA IS: ' || V_AREA);

END;


