SET SERVEROUTPUT ON
DECLARE 
V_EMPNO EMP_1.EMPLOYEE_ID%TYPE :=106;
V_ASTERISK EMP_1.Starts%TYPE :=NULL;
V_SAL EMP_1.SALARY%TYPE;
BEGIN
SELECT ROUND(SALARY/1000) INTO V_SAL FROM EMP_1
WHERE EMPLOYEE_ID= V_EMPNO;
--DBMS_OUTPUT.PUT_LINE('Result: '||V_SAL);
FOR I IN V_SAL LOOP
V_ASTERISK :=V_ASTERISK||'*';
END LOOP;
--DBMS_OUTPUT.PUT_LINE('Result: '||V_ASTERISK);
UPDATE EMP_1 SET Starts =V_ASTERISK
WHERE EMPLOYEE_ID = V_EMPNO;
DBMS_OUTPUT.PUT_LINE('Update ' || SQL%ROWCOUNT || ' ROW');
END;