CREATE OR REPLACE PROCEDURE RAISE_SALARY(
    P_ID      IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    P_PERSENT IN NUMBER)
IS
BEGIN
  UPDATE EMP2 SET SALARY = salary*(1+P_PERSENT/100) WHERE EMPLOYEE_ID = P_ID;
END;

SELECT SALARY FROM EMP2 WHERE EMPLOYEE_ID = 100;

BEGIN
RAISE_SALARY(100, 20);
END;

CREATE OR REPLACE PROCEDURE query_emp(
    P_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    P_NAME OUT EMPLOYEES.LAST_NAME%TYPE,
    P_SALARY OUT EMPLOYEES.SALARY%TYPE)
IS
BEGIN
  SELECT LAST_NAME,
    SALARY
  INTO P_NAME,
    P_SALARY
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = P_ID;
END;


SET SERVEROUTPUT ON;
DECLARE
  V_NAME EMPLOYEES.LAST_NAME%TYPE;
  V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
  query_emp(100,V_NAME,V_SALARY);
  DBMS_OUTPUT.PUT_LINE(V_NAME||' EARNS: '||V_SALARY);
END;