ALTER TABLE EMP_HISTORY
ADD NEW_SAL NUMBER;




UPDATE EMP_HISTORY 
SET NEW_SAL = 0;

CREATE OR REPLACE PROCEDURE NEW_SAL(P_EMP_ID IN NUMBER, P_PCT IN NUMBER)
IS
BEGIN
  UPDATE EMP_HISTORY
  SET NEW_SAL = SAL + (SAL*P_PCT/100)
  WHERE EMPID = P_EMP_ID;
END;

EXECUTE NEW_SAL(105,10);

SELECT * FROM EMP_HISTORY;
