SET SERVEROUTPUT ON;
DECLARE
  V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 106;
  V_ANNUAL_SAL EMPLOYEES.SALARY%TYPE := 0;
BEGIN
  SELECT (SALARY*12)+(NVL(COMMISSION_PCT,0)*12)
  INTO V_ANNUAL_SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = V_EMP_ID;
  DBMS_OUTPUT.PUT_LINE('ANNUAL SALARY IS: '||V_ANNUAL_SAL);
END;
/