SET SERVEROUTPUT ON
DECLARE 
V_LNAME VARCHAR2(10);
EMP_ID NUMBER;
BEGIN
SELECT EMPLOYEE_ID,LAST_NAME INTO EMP_ID,V_LNAME 
FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
DBMS_OUTPUT.PUT_LINE(V_LNAME ||' ID IS ' ||EMP_ID);
END;

--------------------------

SET SERVEROUTPUT ON
DECLARE 
V_LNAME VARCHAR2(10);
EMP_ID NUMBER;

BEGIN
SELECT EMPLOYEE_ID,LAST_NAME INTO EMP_ID,V_LNAME FROM EMPLOYEES;-- WHERE EMPLOYEE_ID = 1000;
DBMS_OUTPUT.PUT_LINE(V_LNAME ||' ID IS ' ||EMP_ID);

EXCEPTION
WHEN no_data_found THEN  
  DBMS_OUTPUT.PUT_LINE('No data');
WHEN TOO_MANY_ROWS THEN
  DBMS_OUTPUT.PUT_LINE('Too many rows');
END;