SET SERVEROUTPUT ON
DECLARE
V_FULL_NAME VARCHAR(100);

BEGIN
SELECT FIRST_NAME||' '||LAST_NAME INTO V_FULL_NAME
fROM EMPLOYEES
WHERE EMPLOYEE_ID IN (&EMP_ID);
DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME IS: ' || V_FULL_NAME);

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');

WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE('TOO MANY DATA FOUND');

END;

