SELECT EMPLOYEE_ID,
  FIRST_NAME||' '||LAST_NAME NAME,
  COMMISSION_PCT COMMISSION
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY 3 ASC;



SELECT FIRST_NAME||' '||LAST_NAME NAME,
  SALARY
FROM EMPLOYEES
WHERE SALARY > &SAL
ORDER BY 2;



SELECT INITCAP(LAST_NAME) NAME,
  LPAD(SALARY,10,'*') SALARY
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'M%'
      OR LAST_NAME LIKE 'T%'
      OR LAST_NAME LIKE 'W%'
ORDER BY 1 ASC;


SELECT LAST_NAME,
       HIRE_DATE,
       TO_CHAR(NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),'Mon'),'FMDay, "the" DdSPTH "of" Month, YYYY') "Salary review date"
FROM EMPLOYEES;