SET SERVEROUTPUT ON
DECLARE
--  V_COUNTER NUMBER := 1;
BEGIN
  FOR I IN 1..10
  LOOP
  CONTINUE WHEN I = 6 OR I = 9;
    DBMS_OUTPUT.PUT_LINE('RESULT: ' || I);
--    V_COUNTER := V_COUNTER + 1;
  END LOOP;
END;
/