
VARIABLE B_VAR NUMBER := 20;
CREATE OR REPLACE FUNCTION RETURN_CITY(
    P_EMP_ID NUMBER)
  RETURN VARCHAR2
IS
  V_CITY VARCHAR2(50) := 'NO CITY FOUND';
BEGIN
  SELECT CITY
  INTO V_CITY
  FROM LOCATIONS
  WHERE LOCATION_ID =
    (SELECT LOCATION_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID =
      (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMP_ID
      )
    ); 
  RETURN V_CITY;
END;
VARI
SELECT RETURN_CITY(100) AS CITY FROM DUAL;