CREATE GLOBAL TEMPORARY TABLE TEMP_TBL(
ID NUMBER,
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR2(100)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE TEMP_TBL_PSV(
ID NUMBER,
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR2(100)
) ON COMMIT PRESERVE ROWS;

SELECT * FROM TEMP_TBL;

SELECT * FROM TEMP_TBL_PSV;

INSERT INTO TEMP_TBL_PSV
VALUES(100,1,'RAM');

COMMIT;