CREATE TABLE STUDENT_INFO(
ROLL_NO NUMBER CONSTRAINT STD_INFO_ROLL_PK PRIMARY KEY,
NAME VARCHAR2(20),
AGE NUMBER CONSTRAINT STD_AGE_CK CHECK (AGE>=5),
BLOOD VARCHAR2(3),
CLASS NUMBER DEFAULT 1
);

CREATE SEQUENCE STD_SEQ 
START WITH 100
INCREMENT BY 1
MAXVALUE 10000000;

ALTER SEQUENCE STD_SEQ  --START WITH NOT ALLOWED IN ALTER SEQUENCE
INCREMENT BY 1
MAXVALUE 10000000
ORDER;



SELECT STD_SEQ.CURRVAL FROM DUAL;
SELECT STD_SEQ.NEXTVAL FROM DUAL;


CREATE SYNONYM STD FOR STUDENT_INFO;

CREATE SYNONYM COUNTRY FOR COUNTIES;
CREATE SYNONYM DEPT FOR STUDENT_INFO;
CREATE PUBLIC SYNONYM EMP FOR EMPLOYEES; --NOT ALLOWED FROM HR USER
CREATE SYNONYM JB_H FOR JOB_HISTORY;
CREATE SYNONYM JB FOR JOBS;
CREATE SYNONYM LOC FOR LOACTIONS;
CREATE SYNONYM REG FOR REGIONS;

SELECT * FROM USER_SYNONYMS;
SELECT * FROM USER_SEQUENCES;

CREATE SYNONYM S_SQ FOR STD_SEQ;

SELECT S_SQ.NEXTVAL FROM DUAL;

DESC USER_SYNONYMS;
DESC USER_SEQUENCES;

SELECT USER FROM USER_TABLES;
SELECT USERNAME FROM DBA_USERS;
DESC DBA_USERS;



CREATE INDEX SAL_INDX
ON EMPLOYEES(SALARY);

SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;

DESC EMPLOYEES;
DESC JOBS;


--------------VIEW------------------
CREATE OR REPLACE VIEW EMP_DTL
AS(
SELECT E.EMPLOYEE_ID ID, E.LAST_NAME NAME, E.SALARY,NVL(COMMISSION_PCT,0) COMM_PCT, D.DEPARTMENT_NAME DEPT, J.JOB_TITLE
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
LEFT JOIN JOBS J
ON(E.JOB_ID = J.JOB_ID)
);

ALTER TABLE STUDENT_INFO RENAME TO STUDENT;
RENAME  EMP_DTL TO EMP;
RENAME STUDENT TO STUDENT_INFO;

SELECT * FROM EMP_DTL;
COMMIT;

DROP VIEW EMP;