CREATE TABLE STUDENT(
  STUDENT_ID NUMBER CONSTRAINT STD_ID_PK PRIMARY KEY,
  FULL_NAME VARCHAR2(50) NOT NULL,
  AGE NUMBER CONSTRAINT STD_AGE_CK CHECK (AGE > 12),
  DOB DATE
  );
  
CREATE TABLE SUBJECT(
  SUBJECT_ID NUMBER CONSTRAINT SUB_ID_PK PRIMARY KEY,
  STUDENT_ID NUMBER,
  SUBJECT_NAME VARCHAR2(50) CONSTRAINT SUB_NAM_UK UNIQUE,
  CONSTRAINT SUB_STD_FK FOREIGN KEY (STUDENT_ID)
  REFERENCES STUDENT(STUDENT_ID) --ON DELETE CASCADE
);

ALTER TABLE SUBJECT
DROP CONSTRAINT SUB_STD_FK;

ALTER TABLE SUBJECT
ADD CONSTRAINT SUB_STD_FK FOREIGN KEY (STUDENT_ID)
  REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE;

CREATE SEQUENCE STD_SQ
START WITH 101
INCREMENT BY 1;

CREATE SEQUENCE SUB_SQ
START WITH 101
INCREMENT BY 1;

INSERT INTO STUDENT(STUDENT_ID,FULL_NAME,AGE,DOB)
VALUES('&STD_ID','&NAME','&AGE','&DOB');

INSERT INTO SUBJECT(SUBJECT_ID,STUDENT_ID,SUBJECT_NAME)
VALUES(SUB_SQ.NEXTVAL,'&STD_ID','&SUB_NAME');

SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;

DELETE FROM STUDENT
WHERE STUDENT_ID IN (102,103,104,105);

UPDATE SUBJECT
SET SUBJECT_NAME ='BUSINEES STUDY'
WHERE STUDENT_ID = 106 AND SUBJECT_NAME = 'ICT';