SET VERIFY OFF;
DECLARE
  V_AGE NUMBER := &AGE;
BEGIN
  IF V_AGE >= 5 THEN
    DBMS_OUTPUT.PUT_LINE(V_AGE||' IS ELIGIBLE FOR ADMIT');
  ELSE
    DBMS_OUTPUT.PUT_LINE(V_AGE||' NOT IS ELIGIBLE FOR ADMIT');
  END IF;
END;