CREATE TABLE EMP_CR
AS
SELECT EMPLOYEE_ID,LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES;


SELECT * FROM EMP_CR;

ALTER TABLE EMP_CR
ADD(DEPARTMENT_NAME VARCHAR2(50));

UPDATE EMP_CR C
SET C.DEPARTMENT_NAME = (SELECT D.DEPARTMENT_NAME
                          FROM DEPARTMENTS D
                          WHERE D.DEPARTMENT_ID = C.DEPARTMENT_ID);
                          
DELETE FROM EMP_CR C
WHERE C.DEPARTMENT_NAME = (SELECT D.DEPARTMENT_NAME
                          FROM DEPARTMENTS D
                          WHERE D.DEPARTMENT_ID = C.DEPARTMENT_ID 
                          AND D.DEPARTMENT_ID = 50);

