SET SERVEROUTPUT ON;
DECLARE
  V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
  V_F_NAME EMPLOYEES.FIRST_NAME%TYPE;
  V_L_NAME EMPLOYEES.LAST_NAME%TYPE;
  V_EMAIL EMPLOYEES.EMAIL%TYPE;
  V_PHN_NUM EMPLOYEES.PHONE_NUMBER%TYPE;
  V_H_DATE EMPLOYEES.HIRE_DATE%TYPE;
  V_JOB_ID EMPLOYEES.JOB_ID%TYPE;
  V_SALARY EMPLOYEES.SALARY%TYPE;
  V_COM_PCT EMPLOYEES.COMMISSION_PCT%TYPE;
  V_MNG_ID EMPLOYEES.MANAGER_ID%TYPE;
  V_DEPT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;

BEGIN
  SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
  INTO V_EMP_ID,V_F_NAME,V_F_NAME,V_EMAIL,V_PHN_NUM,V_H_DATE,V_JOB_ID,V_SALARY,V_COM_PCT,V_MNG_ID,V_DEPT_ID
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = 107;
  
  DBMS_OUTPUT.PUT_LINE('FULL INFO OF EMPLOYEE ID=' || V_EMP_ID ||' ' || 'IS BELLOW');
  DBMS_OUTPUT.PUT_LINE('FRIRST NAEM: '||V_F_NAME);
  DBMS_OUTPUT.PUT_LINE('LAST NAEM: '||V_L_NAME);
  DBMS_OUTPUT.PUT_LINE('EMAIL: '||V_EMAIL);
  DBMS_OUTPUT.PUT_LINE('PHONE NUMBER: '||V_PHN_NUM);
  DBMS_OUTPUT.PUT_LINE('HIRE DATE: '||V_H_DATE);
  DBMS_OUTPUT.PUT_LINE('JOB ID: '||V_JOB_ID);
  DBMS_OUTPUT.PUT_LINE('SALARY: '||V_SALARY);
  DBMS_OUTPUT.PUT_LINE('COMMISSION PCT: '||V_COM_PCT);
  DBMS_OUTPUT.PUT_LINE('MANAGER ID: '||V_MNG_ID);
  DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID: '||V_DEPT_ID);
END;

select * from demo1;
drop table demo1;

rollback;
