CREATE OR REPLACE PROCEDURE FORMATE_PHONE(
P_PHN_NO IN OUT VARCHAR2)
IS
BEGIN
P_PHN_NO := '(' || SUBSTR(P_PHN_NO,1,3) ||
            ') '|| SUBSTR(P_PHN_NO,4,3) ||
            '-' || SUBSTR(P_PHN_NO,7,5);
END;

VARIABLE B_PHN VARCHAR2;
EXECUTE :B_PHN := '80063305759999888';
PRINT B_PHN;
EXECUTE FORMATE_PHONE(:B_PHN);
PRINT B_PHN;