SET SERVEROUTPUT ON;
DECLARE
V_BOOL_VAL BOOLEAN := TRUE;
BEGIN
  IF V_BOOL_VAL THEN
    DBMS_OUTPUT.PUT_LINE('VALUE IS: TRUE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('VALUE IS: FALSE');
  END IF;
END;


DECLARE
V_BOOL_VAL2 BOOLEAN := TRUE;
BEGIN
  IF TRUE THEN
    DBMS_OUTPUT.PUT_LINE('VALUE IS: TRUE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('VALUE IS: FALSE');
  END IF;
END;