SELECT CITY
 -- INTO V_CITY
  FROM LOCATIONS
  WHERE LOCATION_ID =
    (SELECT LOCATION_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID =
      (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 100
      )
    ); 