select job_id,max(salary),min(salary),sum(salary),avg(salary)
from employees;

select job_id,max(salary),min(salary),sum(salary),avg(salary)
from employees
group by job_id;

select job_id,count(*)
from employees
group by job_id;

select job_id,count(*)
from employees
where job_id = '&job'
group by job_id;


SELECT MAX(SALARY)-MIN(SALARY) FROM EMPLOYEES;

SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY)>6000
ORDER BY 2 DESC;


SELECT COUNT(*),
  SUM(DECODE(TO_CHAR(hire_date,'FMYYYY'),2005,1,0)) "2005",
  SUM(DECODE(TO_CHAR(hire_date,'FMYYYY'),2006,1,0)) "2006",
  SUM(DECODE(TO_CHAR(hire_date,'FMYYYY'),2007,1,0)) "2007",
  SUM(DECODE(TO_CHAR(hire_date,'FMYYYY'),2008,1,0)) "2008"
FROM EMPLOYEES;
  
SELECT JOB_ID,
       SUM(DECODE(DEPARTMENT_ID,20,SALARY,NULL)) "DEPT 20",
       SUM(DECODE(DEPARTMENT_ID,50,SALARY,NULL)) "DEPT 50",
       SUM(DECODE(DEPARTMENT_ID,80,SALARY,NULL)) "DEPT 80",
       SUM(DECODE(DEPARTMENT_ID,90,SALARY,NULL)) "DEPT 90",
       SUM(SALARY) TOTAL
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT LOCATION_ID,STREET_ADDRESS,CITY,STATE_PROVINCE,COUNTRY_NAME
FROM LOCATIONS
NATURAL JOIN COUNTRIES;

SELECT LAST_NAME, DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS 
USING(DEPARTMENT_ID);

SELECT LAST_NAME,JOB_ID, DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS 
USING(DEPARTMENT_ID)
JOIN LOCATIONS
USING(LOCATION_ID)
WHERE CITY = 'Toronto';

SELECT E.LAST_NAME EMPLOYEE,E.EMPLOYEE_ID EMP#, M.LAST_NAME MANAGER, M.EMPLOYEE_ID MGR#
FROM EMPLOYEES E JOIN EMPLOYEES M
ON(E.MANAGER_ID = M.EMPLOYEE_ID);


SELECT E.LAST_NAME EMPLOYEE,E.EMPLOYEE_ID EMP#, M.LAST_NAME MANAGER, M.EMPLOYEE_ID MGR#
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
ON(E.MANAGER_ID = M.EMPLOYEE_ID);


SELECT E.LAST_NAME,E.DEPARTMENT_ID,C.LAST_NAME
FROM EMPLOYEES E JOIN EMPLOYEES C
ON(

