CREATE TABLE DEPT AS
SELECT * FROM DEPARTMENTS;
DROP TABLE DEPT;
SELECT * FROM DEPT;

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE ADD_DEPT
IS
  V_DEPT_ID   NUMBER;
  V_DEPT_NAME VARCHAR2(50);
BEGIN
  V_DEPT_ID   := 280;
  V_DEPT_NAME := 'HEAD OF IT';
  INSERT INTO DEPT
    (DEPARTMENT_ID,DEPARTMENT_NAME
    ) VALUES
    (V_DEPT_ID,V_DEPT_NAME
    );
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT||' ROW INSERTED');
END;
BEGIN
CALL ADD_DEPT;
END;