CREATE VIEW EMPLOYEE_SUMMARY
AS
SELECT E.EMPLOYEE_ID AS IDENTITY, E.FIRST_NAME||' '||E.LAST_NAME AS NAME, ((NVL(E.COMMISSION_PCT,0)*E.SALARY)+E.SALARY)*12 YEARLY_SALARY, L.CITY, R.REGION_NAME CONTINENT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(L.LOCATION_ID = D.LOCATION_ID)
JOIN COUNTRIES C
ON(C.COUNTRY_ID = L.COUNTRY_ID)
JOIN REGIONS R
ON(R.REGION_ID = C.REGION_ID);

SELECT E.EMPLOYEE_ID AS IDENTITY, E.FIRST_NAME||' '||E.LAST_NAME AS NAME, ((NVL(E.COMMISSION_PCT,0)*E.SALARY)+E.SALARY)*12 YEARLY_SALARY, L.CITY, R.REGION_NAME CONTINENT
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
AND (L.LOCATION_ID = D.LOCATION_ID)
AND (C.COUNTRY_ID = L.COUNTRY_ID)
AND (R.REGION_ID = C.REGION_ID);

DESC LOCATIONS;
DESC COUNTRIES;
DESC REGIONS;


CREATE TABLE PHONE_BRAND(
BRAND_ID NUMBER CONSTRAINT BRAND_ID_PK PRIMARY KEY,
BRAND_NAME VARCHAR2(50) CONSTRAINT BRAND_NAME_UK UNIQUE,
ESTABLISHED VARCHAR2(4) NOT NULL,
REMARKS VARCHAR2(100)
);

CREATE SEQUENCE PHONR_BRAND_SEQ
START WITH 105
INCREMENT BY 5;

INSERT INTO PHONE_BRAND
VALUES(PHONR_BRAND_SEQ.NEXTVAL, '&NAME', '&EST','&REMARKS');

INSERT INTO PHONE_BRAND
VALUES(PHONR_BRAND_SEQ.NEXTVAL, 'NOKIA', 2000,'GOOD');

SELECT * FROM PHONE_BRAND;

CREATE SYNONYM b_id_seq
FOR PHONR_BRAND_SEQ;

INSERT INTO PHONE_BRAND
VALUES(b_id_seq.NEXTVAL, '&NAME', '&EST','&REMARKS');

ALTER TABLE PHONE_BRAND
ADD( GREAD CHAR(1) DEFAULT 'A' CONSTRAINT P_BRAND_GREAD_NN  NOT NULL ,
     COUNTRY VARCHAR2(100) DEFAULT 'BANGLADESH' CONSTRAINT P_BRAND_COUNTRY_NN NOT NULL 
     );
     
CREATE INDEX BRAND_NAME_INX
ON PHONE_BRAND (ESTABLISHED);

SELECT * FROM USER_INDEXES
WHERE TABLE_NAME = 'PHONE_BRAND';

SELECT INDEX_NAME,TABLE_NAME FROM USER_INDEXES
WHERE TABLE_NAME = 'PHONE_BRAND';


SELECT E.EMPLOYEE_ID,E.LAST_NAME,E.SALARY, ROUND(AVG(N.SALARY))
FROM EMPLOYEES E JOIN EMPLOYEES N
ON( E.DEPARTMENT_ID = N.DEPARTMENT_ID)
GROUP BY N.DEPARTMENT_ID,E.LAST_NAME,E.SALARY,E.EMPLOYEE_ID
ORDER BY 2 ASC;

 SELECT LAST_NAME, HIRE_DATE,ADD_MONTHS(HIRE_DATE,(TRUNC((SYSDATE-HIRE_DATE)/30)))
 FROM EMPLOYEES;
 
 
 SELECT TABLE_NAME FROM USER_TABLES;
 
 
 
 SELECT LAST_NAME, HIRE_DATE, DATEADD(HIRE_DATE,SYSDATE)
 FROM EMPLOYEES;
 
 SELECT
      SYSDATE,HIRE_DATE,
      HIRE_DATE
      + TO_YMINTERVAL ( '1-0' )
FROM
      EMPLOYEES;