SET SERVEROUTPUT ON;
DECLARE
  CURSOR EMP_CUR(DEPT_ID NUMBER) IS
  SELECT ROWNUM, EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
  WHERE DEPARTMENT_ID = DEPT_ID;
  V_EMP EMP_CUR%ROWTYPE;
  V_ID NUMBER;
BEGIN
  OPEN EMP_CUR(&ID);
  LOOP
    FETCH EMP_CUR INTO V_EMP;
    DBMS_OUTPUT.PUT_LINE(V_EMP.EMPLOYEE_ID||' '||V_EMP.LAST_NAME);
    EXIT WHEN EMP_CUR%NOTFOUND;
  END LOOP;
END;