SET SERVEROUTPUT ON;
DECLARE
  CURSOR EMP_CUR IS
  SELECT ROWNUM, EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES;
  V_EMP EMP_CUR%ROWTYPE;
  
BEGIN
  OPEN EMP_CUR;
  LOOP
    FETCH EMP_CUR INTO V_EMP;
    DBMS_OUTPUT.PUT_LINE(V_EMP.EMPLOYEE_ID||' '||V_EMP.LAST_NAME);
    EXIT WHEN EMP_CUR%NOTFOUND;
  END LOOP;
  
  IF EMP_CUR%ISOPEN THEN
    CLOSE EMP_CUR;
  END IF;
END;