SET SERVEROUTPUT ON
DECLARE
  V_EMP_ID  NUMBER;
  V_SAL     NUMBER;
  V_COMM    NUMBER;
  V_ANN_SAL NUMBER := 0;    --INNITIALIGE VARIABLE VALUE
BEGIN
  SELECT EMPLOYEE_ID,NVL(SALARY,0),NVL(COMMISSION_PCT,0)
  INTO V_EMP_ID,V_SAL,V_COMM
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = 151;
  
  --V_ANN_SAL := 0;
  V_ANN_SAL := (V_SAL + (V_SAL*V_COMM))*12;
  
  DBMS_OUTPUT.PUT_LINE('ANNUAL SALARY OF EMPLOYEE IS '||V_EMP_ID||' IS ' ||V_ANN_SAL);
END;