SET SERVEROUTPUT ON;
DECLARE
  TYPE T_REC IS RECORD
    (V_SAL NUMBER,
    V_HIRE_DATE DATE,
    V_REC1 EMPLOYEES%ROWTYPE);
  V_MYREC T_REC;
  TYPE T_ASS_ARRY IS TABLE OF
    V_MYREC%ROWTYPE INDEX BY PLS_INTIGER;
  
BEGIN
  V_MYREC.V_SAL := 500;
  SELECT * INTO V_MYREC.V_REC1 FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
  
  DBMS_OUTPUT.PUT_LINE(V_MYREC.V_REC1.EMPLOYEE_ID ||'  '||V_MYREC.V_SAL);
END;

