SET SERVEROUTPUT ON;
DECLARE
  CURSOR CUR_DETP IS 
    SELECT * --DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID
    FROM DEPARTMENTS;
  
  V_DEPT_ID NUMBER;
  V_DEPT_NAME VARCHAR2(50);
  V_MANAGER_ID NUMBER;
BEGIN
  OPEN CUR_DETP;
  FETCH CUR_DETP.DEPARTMENT_ID INTO V_DEPT_ID, V_DEPT_NAME,V_MANAGER_ID;
  
  DBMS_OUTPUT.PUT_LINE(V_DEPT_ID||' '||V_DEPT_NAME||' '||V_MANAGER_ID);
  CLOSE CUR_DEPT;
END;

