SET SERVEROUTPUT ON;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Today''s Date: '|| TO_CHAR(SYSDATE,'FM DD Month YYYY'));
  DBMS_OUTPUT.PUT_LINE('Tomorrow''S Date: '|| TO_CHAR(SYSDATE + 1,'FM DD Month YYYY'));
END;