SELECT EMPLOYEE_ID,
  LAST_NAME,
  RPAD('*',LENGTH(LAST_NAME),'*') star
FROM EMPLOYEES;
SELECT EMPLOYEE_ID,
  FIRST_NAME
  ||' '
  ||LAST_NAME,
  SALARY,
  DEPARTMENT_ID
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME
  ||' '
  ||LAST_NAME) LIKE UPPER('&NAME%')
ORDER BY 2;
SELECT FIRST_NAME
  ||' '
  ||LAST_NAME
  ||' joned the company on '
  ||TO_CHAR(HIRE_DATE,'FMddspth Month "of" YYYY')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;


SELECT D.DEPARTMENT_NAME "Department",
  TO_CHAR(SUM(E.SALARY),'99g99g999D00') AS "Total Salary",
  TO_CHAR(MAX(E.SALARY),'99g99g999D00') AS "Highest Salary",
  TO_CHAR(MIN(E.SALARY),'99g99g999D00') AS "Lowest Salary",
  TO_CHAR(AVG(E.SALARY),'99g99g999D00') AS "Average Salary"
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME
HAVING MIN(E.SALARY) > 6000
ORDER BY 2 DESC;






