SET SERVEROUTPUT ON
DECLARE
  TYPE  T_REC IS RECORD
    (V_SAL NUMBER(8),
    V_MIN_SAL NUMBER DEFAULT 1000,
    V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE,
    V_REC1 EMPLOYEES%ROWTYPE
    );
  V_MYREC T_REC;
  
BEGIN
  V_MYREC.V_SAL := V_MYREC. V_MIN_SAL + 500;
  V_MYREC.V_HIRE_DATE := SYSDATE;
  SELECT EMPLOYEE_ID, LAST_NAME INTO V_MYREC.V_REC1.EMPLOYEE_ID,V_MYREC.V_REC1.LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
  DBMS_OUTPUT.PUT_LINE(V_MYREC.V_REC1.EMPLOYEE_ID||' '||V_MYREC.V_REC1.LAST_NAME||' '|| V_MYREC.V_HIRE_DATE||' '||V_MYREC.V_SAL);
  SELECT * INTO V_MYREC.V_REC1 FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
  DBMS_OUTPUT.PUT_LINE(V_MYREC.V_REC1.EMPLOYEE_ID);
END;