SET SERVEROUTPUT ON;

DECLARE
V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE := '&L_NAME';

BEGIN
  SELECT FIRST_NAME
  INTO V_FIRST_NAME
  FROM EMPLOYEES
  WHERE UPPER(LAST_NAME) = UPPER(V_LAST_NAME);
  DBMS_OUTPUT.PUT_LINE(V_LAST_NAME||' FIRST NAME IS: '||V_FIRST_NAME);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN
    FOR I IN (SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(LAST_NAME) = UPPER(V_LAST_NAME)) LOOP
    DBMS_OUTPUT.PUT_LINE(V_LAST_NAME||' FIRST NAME IS: '||I.FIRST_NAME);
    END LOOP;
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO EMPLOYEE FOUND WITH LAST NAME: '||V_LAST_NAME);
END;

SELECT * FROM EMPLOYEES;