CREATE TABLE STUDENT_INFO
  (
    ID        NUMBER,
    FULE_NAME VARCHAR2(50),
    SUBJECT   VARCHAR2(30)
  );
  
  
INSERT INTO STUDENT_INFO VALUES
  (100,'khi','CCO'
  );

SELECT * FROM STUDENT_INFO;
ROLLBACK;
  
CREATE OR REPLACE TRIGGER STD_ADD_RESTRICT 
BEFORE INSERT ON STUDENT_INFO
BEGIN 
  IF TO_CHAR(SYSDATE,'FMHH:MI AM') BETWEEN '09:00 AM' AND '03:00 PM' THEN 
    RAISE_APPLICATION_ERROR(-20990,'STUDENT ADD NOT ALLOW IN 09:00 AM TO 03:00 PM!');
  END IF;
END;


SELECT TO_CHAR(SYSDATE,'HH:MI AM') FROM DUAL;